### ISSUE TITLE
ClassCastException for Private Key

### ISSUE THREAD

**Issue by ThothTrustCom** [martinpaljak/capfile#30]
I am receiving a ClassCastException for ' java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair'.

The release version is Release v20.08.12.

java -jar capfile.jar -s dap.pem isoapplet.cap
CAP file (v2.2), contains: applets for JavaCard 3.0.4
Package: net.pwendland.javacard.pki.isoapplet F276A288BCFBA69D34F310 v1.0
Applet:  net.pwendland.javacard.pki.isoapplet.IsoApplet F276A288BCFBA69D34F31001
Import:  A0000000620001                   v1.0 java.lang
Import:  A0000000620101                   v1.5 javacard.framework
Import:  A0000000620209                   v1.0 javacardx.apdu
Import:  A0000000620102                   v1.5 javacard.security
Import:  A0000000620201                   v1.5 javacardx.crypto
Generated by Oracle Corporation converter  [v3.0.4]
On Sat Sep 19 15:10:44 SGT 2020 with JDK 1.8.0 (Oracle Corporation)
Code size 12007 bytes (36793 with debug)
SHA-256 2a643088c767c007e001380454d6ead025f1bdb8d1f29a7356232507bfff33fa
SHA-1   ee03a5391c167e827b1a55dbc6162c91925d826a
Exception in thread "main" java.lang.ClassCastException: org.bouncycastle.asn1.pkcs.PrivateKeyInfo cannot be cast to org.bouncycastle.openssl.PEMKeyPair
        at pro.javacard.CAPFileSigner.pem2keypair(CAPFileSigner.java:91)
        at pro.javacard.CAPFileTool.main(CAPFileTool.java:55)

**Comment by ThothTrustCom** [comment]
Found issue being the dap.pem is corrupted which prevents proper casting.

**Comment by martinpaljak** [comment]
This is a valid enhancement
